#!/usr/bin/env python

import sys
import csv
import json
import argparse


parser = argparse.ArgumentParser()
parser.add_argument("files", help="path to CSVs, default stdin", nargs="*")

args = parser.parse_args()

files = args.files
if not files:
    files = ["-"]

for file in files:
    if file == "-":
        infp = sys.stdin
    else:
        infp = open(file, "r")

    reader = csv.DictReader(infp)
    for row in reader:
        sys.stdout.write(json.dumps(row) + "\n")

    if file != "-":
        infp.close()

